---
name: Storefront (fixed) Service Test and Build

"on":
  push:
    branches:
      - main
    paths:
      - store-frontend/**
  workflow_dispatch:
    branches: [main]

defaults:
  run:
    working-directory: store-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v2.2
        id: short-sha

      - name: Get current timestamp
        id: timestamp
        run: echo "now=$(date +'%s')" >> "$GITHUB_OUTPUT"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.IAM_GA_ROLE }}
          aws-region: "us-east-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 453834546898

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          AWS_ACCOUNT: 453834546898
          ECR_REPOSITORY: storefront
          ECR_REGION: us-east-1
          IMAGE_TAG: "${{ steps.timestamp.outputs.now }}-${{ steps.short-sha.outputs.sha }}"
        run: |
          docker build -t "$ECR_REPOSITORY:$IMAGE_TAG" -f storefront-versions/store-frontend-instrumented-fixed/Dockerfile .
          docker tag "$ECR_REPOSITORY:$IMAGE_TAG" "$AWS_ACCOUNT.dkr.ecr.$ECR_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$AWS_ACCOUNT.dkr.ecr.$ECR_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
